/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistema.view;

import br.com.sistema.model.Feedback;
import br.com.sistema.dao.FeedbackDAO;
import br.com.sistema.dao.ClientesDAO;
import br.com.sistema.model.Utilitarios;
import br.com.sistema.model.Clientes;
import java.awt.Color;
import java.util.List;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alunos
 */
public class FrmFeedback extends javax.swing.JFrame {

    //Metodo Listar na tabela
    public void listar() {

        FeedbackDAO dao = new FeedbackDAO();
        List<Feedback> lista = dao.listarFeedbacks();
        DefaultTableModel dados = (DefaultTableModel) tabelaFeedback.getModel();
        dados.setNumRows(0);

        for (Feedback c : lista) {
            dados.addRow(new Object[]{
                c.getData_feedback(),
                c.getId(),
                c.getCliente().getId(),
                c.getCliente().getNome(),
                c.getCliente().getEmail(),
                c.getCliente().getTelefone(),
                c.getDescricao()
            });

        }

    }

    DefaultListModel MODELO;
    int enter = 0;

    /**
     * Creates new form FrmFeedback
     */
    public FrmFeedback() {
        initComponents();
        ListaNomes.setVisible(false);
        MODELO = new DefaultListModel();
        ListaNomes.setModel(MODELO);
        this.getContentPane().setBackground(Color.WHITE);

        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.gray);
        headerRenderer.setForeground(Color.WHITE);

        for (int i = 0; i < tabelaFeedback.getModel().getColumnCount(); i++) {
            tabelaFeedback.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnnovo = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFeedback = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        txtpesquisa = new javax.swing.JTextField();
        btnpesquisar = new javax.swing.JButton();
        painel_dados = new javax.swing.JPanel();
        ListaNomes = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txttel = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txtdescricao = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txtidcliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtidfeedback = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnnovo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo.png"))); // NOI18N
        btnnovo.setText("Novo");
        btnnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovoActionPerformed(evt);
            }
        });
        jPanel2.add(btnnovo);

        btnsalvar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        btnsalvar.setText("Salvar");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btnsalvar);

        btneditar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        jPanel2.add(btneditar);

        btnexcluir.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        btnexcluir.setText("Excluir");
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });
        jPanel2.add(btnexcluir);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 1200, 100));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setFocusable(false);
        jTabbedPane1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel4ComponentShown(evt);
            }
        });

        tabelaFeedback.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tabelaFeedback.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Id feedback", "Id cliente", "Nome", "E-mail", "Telefone", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaFeedback.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabelaFeedback.setAutoscrolls(false);
        tabelaFeedback.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelaFeedback.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        tabelaFeedback.setShowGrid(true);
        tabelaFeedback.setShowVerticalLines(false);
        tabelaFeedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFeedbackMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaFeedback);
        if (tabelaFeedback.getColumnModel().getColumnCount() > 0) {
            tabelaFeedback.getColumnModel().getColumn(0).setResizable(false);
            tabelaFeedback.getColumnModel().getColumn(1).setResizable(false);
            tabelaFeedback.getColumnModel().getColumn(2).setResizable(false);
            tabelaFeedback.getColumnModel().getColumn(3).setResizable(false);
            tabelaFeedback.getColumnModel().getColumn(4).setResizable(false);
            tabelaFeedback.getColumnModel().getColumn(5).setResizable(false);
            tabelaFeedback.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setText("Nome:");

        txtpesquisa.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpesquisaKeyPressed(evt);
            }
        });

        btnpesquisar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnpesquisar.setText("Pesquisar");
        btnpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(9, 9, 9)
                .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnpesquisar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel16))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnpesquisar)))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta", jPanel4);

        painel_dados.setBackground(new java.awt.Color(255, 255, 255));
        painel_dados.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        painel_dados.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                painel_dadosComponentShown(evt);
            }
        });
        painel_dados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ListaNomes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ListaNomes.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        ListaNomes.setMinimumSize(null);
        ListaNomes.setPreferredSize(new java.awt.Dimension(200, 100));
        ListaNomes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ListaNomesMousePressed(evt);
            }
        });
        painel_dados.add(ListaNomes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 400, 150));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Nome:");
        painel_dados.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 70, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Telefone:");
        painel_dados.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 170, -1));

        txttel.setEditable(false);
        try {
            txttel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txttel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txttel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelActionPerformed(evt);
            }
        });
        painel_dados.add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 170, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Email:");
        painel_dados.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 157, -1));

        txtemail.setEditable(false);
        txtemail.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        painel_dados.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 440, -1));

        txtdescricao.setColumns(20);
        txtdescricao.setRows(5);
        txtdescricao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 73, 74)));
        painel_dados.add(txtdescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 1050, 240));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Descrição:");
        painel_dados.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 89, -1));

        txtnome.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnomeKeyReleased(evt);
            }
        });
        painel_dados.add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 403, -1));

        txtidcliente.setEditable(false);
        txtidcliente.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtidcliente.setOpaque(true);
        painel_dados.add(txtidcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 180, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Código Cliente:");
        painel_dados.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        txtidfeedback.setEditable(false);
        txtidfeedback.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        painel_dados.add(txtidfeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 180, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Código Feedback:");
        painel_dados.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jTabbedPane1.addTab("Sugestão e Feedback", painel_dados);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 115, 1200, 580));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("       Sugestões e Feedback");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovoActionPerformed
        new Utilitarios().LimpaTela(painel_dados);
        btnsalvar.setEnabled(true);// habilita o botão salvar
        btneditar.setEnabled(false);// desabilita o botão editar
        btnexcluir.setEnabled(false);// desabilita o botão escluir
        btnnovo.setEnabled(true);// habilita o botão escluir
    }//GEN-LAST:event_btnnovoActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // boto salvar
        int lib = 0;
        String msg = "Os Campos: \n";

        if (txtnome.getText().equals("")) {//campo nome vazio
            msg += "\n Nome ";
            lib++;
        }

        if (lib == 0) {

            Feedback obj = new Feedback();
            ClientesDAO cd = new ClientesDAO();
            Date agora = new Date();
            SimpleDateFormat dataEUA = new SimpleDateFormat("yyyy-MM-dd");
            String datamysql = dataEUA.format(agora);

            obj.setCliente(cd.buscaporid(Integer.parseInt(txtidcliente.getText())));
            obj.setData_feedback(datamysql);
            obj.setDescricao(txtdescricao.getText());

            FeedbackDAO dao = new FeedbackDAO();

            dao.cadastrarFeedback(obj);

            new Utilitarios().LimpaTela(painel_dados);

        } else {
            msg += "\n\n Estão Vazios.";
            JOptionPane.showMessageDialog(null, msg, "ERRO AO CADASTRAR ", HEIGHT);
        }
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // botao editar

        Feedback obj = new Feedback();
        ClientesDAO cd = new ClientesDAO();
        Date agora = new Date();
        SimpleDateFormat dataEUA = new SimpleDateFormat("yyyy-MM-dd");
        String datamysql = dataEUA.format(agora);

        obj.setCliente(cd.buscaporid(Integer.parseInt(txtidcliente.getText())));
        obj.setData_feedback(datamysql);
        obj.setDescricao(txtdescricao.getText());
        obj.setId(Integer.parseInt(txtidfeedback.getText()));

        FeedbackDAO dao = new FeedbackDAO();

        dao.alterarFeedback(obj);

        new Utilitarios().LimpaTela(painel_dados);
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
        // botao excluir

        Feedback obj = new Feedback();

        obj.setId(Integer.parseInt(txtidcliente.getText()));

        FeedbackDAO dao = new FeedbackDAO();

        dao.excluirFeedback(obj);
        new Utilitarios().LimpaTela(painel_dados);

        btnsalvar.setEnabled(true);// habilita o botão salvar
        btneditar.setEnabled(false);// desabilita o botão editar
        btnexcluir.setEnabled(false);// desabilita o botão escluir
        btnnovo.setEnabled(true);// habilita o botão escluir
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void tabelaFeedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFeedbackMouseClicked
        //Pega os dados
        jTabbedPane1.setSelectedIndex(1);

        txtidfeedback.setText(tabelaFeedback.getValueAt(tabelaFeedback.getSelectedRow(), 1).toString());
        txtidcliente.setText(tabelaFeedback.getValueAt(tabelaFeedback.getSelectedRow(), 2).toString());
        txtnome.setText(tabelaFeedback.getValueAt(tabelaFeedback.getSelectedRow(), 3).toString());
        txtemail.setText(tabelaFeedback.getValueAt(tabelaFeedback.getSelectedRow(), 4).toString());
        txttel.setText(tabelaFeedback.getValueAt(tabelaFeedback.getSelectedRow(), 5).toString());
        txtdescricao.setText(tabelaFeedback.getValueAt(tabelaFeedback.getSelectedRow(), 6).toString());
    }//GEN-LAST:event_tabelaFeedbackMouseClicked

    private void txtpesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisaKeyPressed
        String nome = "%" + txtpesquisa.getText() + "%";

        FeedbackDAO dao = new FeedbackDAO();
        List<Feedback> lista = dao.listarFeedbacksPorNome(nome);

        DefaultTableModel dados = (DefaultTableModel) tabelaFeedback.getModel();
        dados.setNumRows(0);

        for (Feedback c : lista) {
            dados.addRow(new Object[]{
                c.getData_feedback(),
                c.getCliente().getId(),
                c.getCliente().getNome(),
                c.getCliente().getEmail(),
                c.getCliente().getTelefone(),
                c.getDescricao()
            });
        }
    }//GEN-LAST:event_txtpesquisaKeyPressed

    private void btnpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisarActionPerformed
        // Botao pesquisar
        String nome = "%" + txtpesquisa.getText() + "%";

        FeedbackDAO dao = new FeedbackDAO();
        List<Feedback> lista = dao.listarFeedbacksPorNome(nome);

        DefaultTableModel dados = (DefaultTableModel) tabelaFeedback.getModel();
        dados.setNumRows(0);

        for (Feedback c : lista) {
            dados.addRow(new Object[]{
                c.getData_feedback(),
                c.getId(),
                c.getCliente().getId(),
                c.getCliente().getNome(),
                c.getCliente().getEmail(),
                c.getCliente().getTelefone(),
                c.getDescricao()
            });
        }
    }//GEN-LAST:event_btnpesquisarActionPerformed

    private void jPanel4ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel4ComponentShown
        // TODO add your handling code here:
        btnsalvar.setEnabled(false);// desabilita o botão salvar
        btneditar.setEnabled(false);// desabilita o botão editar
        btnexcluir.setEnabled(false);// desabilita o botão escluir
        btnnovo.setEnabled(false);// desabilita o botão escluir
    }//GEN-LAST:event_jPanel4ComponentShown

    private void painel_dadosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_painel_dadosComponentShown
        // TODO add your handling code here:
        if (txtidcliente.getText().equals("")) {
            btnsalvar.setEnabled(true);// habilita o botão salvar
            btneditar.setEnabled(false);// desabilita o botão editar
            btnexcluir.setEnabled(false);// desabilita o botão escluir
            btnnovo.setEnabled(true);// habilita o botão escluir
        } else {
            btnsalvar.setEnabled(false);// desabilita o botão salvar
            btneditar.setEnabled(true);// habilita o botão editar
            btnexcluir.setEnabled(true);// habilita o botão escluir
            btnnovo.setEnabled(true);// habilita o botão escluir
        }
    }//GEN-LAST:event_painel_dadosComponentShown

    private void txttelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        ListaNomes.setVisible(false);
        enter = 1;
    }//GEN-LAST:event_txtnomeActionPerformed

    private void txtnomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyReleased
        if (enter == 0) {
            String nome = "%" + txtnome.getText() + "%";
            FeedbackDAO dao = new FeedbackDAO();
            MODELO = new DefaultListModel();
            ListaNomes.setModel(MODELO);
            MODELO.removeAllElements();
            int v = 0;

            List<Clientes> lista = dao.listarNomes(nome);

            for (Clientes c : lista) {
                MODELO.addElement(c.getNome());
                v++;
                if (v == 4) {
                    break;
                }
            }
            if (v > 0) {
                ListaNomes.setVisible(true);
            } else {
                ListaNomes.setVisible(false);
            }

        } else {
            enter = 0;
        }
    }//GEN-LAST:event_txtnomeKeyReleased

    private void ListaNomesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaNomesMousePressed
        ListaNomes.setVisible(false);
        Clientes c = new Clientes();
        ClientesDAO dao = new ClientesDAO();

        c = dao.consultaPorNome(ListaNomes.getSelectedValue().toString());

        txtidcliente.setText(String.valueOf(c.getId()));
        txtnome.setText(c.getNome());
        txttel.setText(c.getTelefone());
        txtemail.setText(c.getEmail());
    }//GEN-LAST:event_ListaNomesMousePressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        new Utilitarios().LimpaTela(painel_dados);
        listar();
    }//GEN-LAST:event_jPanel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFeedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListaNomes;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btnnovo;
    private javax.swing.JButton btnpesquisar;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel painel_dados;
    private javax.swing.JTable tabelaFeedback;
    private javax.swing.JTextArea txtdescricao;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtidcliente;
    private javax.swing.JTextField txtidfeedback;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtpesquisa;
    private javax.swing.JFormattedTextField txttel;
    // End of variables declaration//GEN-END:variables
}
